sudo: false
language: python
cache: pip
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
env:
- DJANGO=1.8
- DJANGO=1.9
- DJANGO=1.10
- DJANGO=1.11
- DJANGO=2.0
matrix:
  exclude:
  - python: 2.7
    env: DJANGO=2.0
  - python: 3.3
    env: DJANGO=1.9
  - python: 3.3
    env: DJANGO=1.10
  - python: 3.3
    env: DJANGO=1.11
  - python: 3.3
    env: DJANGO=2.0
  - python: 3.6
    env: DJANGO=1.8
  - python: 3.6
    env: DJANGO=1.9
  - python: 3.6
    env: DJANGO=1.10
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=flake8
install: pip install tox-travis codecov
script: tox
after_success: coverage combine && codecov
branches:
  only:
  - master
  - "/^v?\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
deploy:
  provider: pypi
  user: jwilhelm
  password:
    secure: NdXz++qJySSRCOS8HSgapo9t07a4We5U5Jtb7CLKMgraepJTw2mlqTq1+KlHNrUsI7Q+SfxAvpIOopNTlwDlj6Y9ppvThuTFrx3l2XQdfrnV4Lzy7VVKrEEAhCsp9gxJ7NkREBcaqP9z9tVl/mzJCKsZhnVNawVli/wifWXZ3GADgA9W8UqEn75BPUMXtO8eozRCPPKXFb5ZDD7y6YHwJAa36WifQZJmrPWzj4FEMTrvSV7AmQ0HJNw2p1aXr5GE1mW05k3DAsEHmaQVm3s0+ajfF1UVX1ijccKZEtXbzxuW+2cICyF+dMwduj/aVihlI7VBdzBhRK5NJ6FyNnCroJTfA2Oei42AmyIN9SVb17hYbIGnQ7YPGspQlG1Pj+qLS0EVMK3a8p6TQatG7qAlKRoNqRiFEJwGL5TYrJDAagI2ysYMHkJLO67F7TzTY2KHRMCYDsCv2CIlUKkZZNXikb4C/3M9o1EMOv613P9PS1hD5AS0wGpqFdFYlJEQC1unKIsOed8ofWz6JjelXCM+tfF8MOsTmy1o4vPtpymOyBiWJjd2DHgsCZXnwHXXzqrpwowjJHvgs8p5Dajv/QbfCa3/iaC+W3d8TsWoumcbJrnTaWMjvOT06XTOvwtAaDXgE8gLkTt6fYtW6o+q8T3GwenDG1iAi51iX+3L5nwG4ks=
  on:
    tags: true
    python: 3.6
    condition: $TOXENV = flake8
    distributions: sdist bdist_wheel
    repo: tarkatronic/django-excel-response
